# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/isssm',
                'doc_host': 'https://stefanheyder.github.io',
                'git_url': 'https://github.com/stefanheyder/isssm',
                'lib_path': 'isssm'},
  'syms': {'isssm.core': {'isssm.core.foo': ('core.html#foo', 'isssm/core.py')}}}
