# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_example_models.ipynb.

# %% auto 0
__all__ = ['lcm', 'common_factor_lcm']

# %% ../nbs/01_example_models.ipynb 3
import jax.numpy as jnp
def lcm(n, x0, s2_x0, s2_eps, s2_eta):
    A = jnp.ones((n, 1, 1))
    B = jnp.ones((n + 1, 1, 1))

    Sigma = jnp.concatenate((s2_x0 * jnp.ones((1, 1, 1)), s2_eps * jnp.ones((n, 1, 1))))
    Omega = jnp.ones((n + 1, 1, 1)) * s2_eta

    x0 = jnp.array(x0).reshape((1,))

    return x0, A, B, Sigma, Omega

# %% ../nbs/01_example_models.ipynb 6
def common_factor_lcm(n, x0, Sigma0, s2_eps, s2_eta):

    if x0.shape != (3,):
        raise ValueError(f"x0 does not have the correct shape, expected (3,) but got {x0.shape}")
    
    A = jnp.broadcast_to(jnp.eye(3), (n, 3, 3))
    B = jnp.broadcast_to(jnp.array([[1,0,1], [0,1,1]]), (n+1,2,3))
    Sigma = jnp.concatenate(
        (Sigma0[None], s2_eps * jnp.broadcast_to(jnp.eye(3), (n,3,3)))
    )
    Omega = s2_eta * jnp.broadcast_to(jnp.eye(2), (n+1,2,2))
    
    return x0, A, B, Sigma, Omega
