# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99_typings.ipynb.

# %% auto 0
__all__ = ['InitialState']

# %% ../nbs/99_typings.ipynb 2
from jaxtyping import Float, Array

# %% ../nbs/99_typings.ipynb 3
InitialState = Float[Array, "m"]
