# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99_util.ipynb.

# %% auto 0
__all__ = ['LOFM', 'MVN_degenerate']

# %% ../nbs/99_util.ipynb 2
import jax.numpy as jnp
from jaxtyping import Array
import tensorflow_probability.substrates.jax as tfp
from tensorflow_probability.substrates.jax.distributions import MultivariateNormalLinearOperator as MVNLO


# %% ../nbs/99_util.ipynb 5
LOFM = tfp.tf2jax.linalg.LinearOperatorFullMatrix
def MVN_degenerate(loc: Array, cov: Array) -> tfp.distributions.MultivariateNormalLinearOperator:
    evals, evecs = jnp.linalg.eigh(cov)
    sqrt_cov = jnp.einsum('...ij,...j->...ij', evecs, jnp.sqrt(evals))
    return MVNLO(loc=loc, scale=LOFM(sqrt_cov))
