repos:
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1  # Use the latest version available
    hooks:
    -   id: nbqa-black
        additional_dependencies: [black==23.7.0]
    -   id: nbqa-isort
        additional_dependencies: [isort==5.12.0]
-   repo: https://github.com/fastai/nbdev
    rev: 2.3.13  # Use the latest version available
    hooks:
    -   id: nbdev_export

